/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAnnihilator } from "./IAnnihilator";
export type { IEnergy } from "./IEnergy";
export type { IOtoms } from "./IOtoms";
export type { IOtomsDatabase } from "./IOtomsDatabase";
export type { IOtomsDatabaseV2 } from "./IOtomsDatabaseV2";
export type { IOtomsEncoder } from "./IOtomsEncoder";
export type { IReactionOutputs } from "./IReactionOutputs";
export type { IReactor } from "./IReactor";
