/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAnnihilator,
  IAnnihilatorInterface,
} from "../../../../src/otom/interfaces/IAnnihilator";

const _abi = [
  {
    inputs: [],
    name: "InputTooLarge",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "InsufficientBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidBPS",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidUniverseHash",
    type: "error",
  },
  {
    inputs: [],
    name: "NegativeResult",
    type: "error",
  },
  {
    inputs: [],
    name: "NoAtoms",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "annihilatedBy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "atomIds",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "energyAmount",
        type: "uint256",
      },
    ],
    name: "Annihilated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "atomIds",
        type: "uint256[]",
      },
    ],
    name: "annihilate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
    ],
    name: "raiseToNucleonsExponent",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_energy",
        type: "address",
      },
    ],
    name: "setEnergy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "_exponentWad",
        type: "int256",
      },
    ],
    name: "setNucleonsExponent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_otoms",
        type: "address",
      },
    ],
    name: "setOtoms",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAnnihilator__factory {
  static readonly abi = _abi;
  static createInterface(): IAnnihilatorInterface {
    return new Interface(_abi) as IAnnihilatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAnnihilator {
    return new Contract(address, _abi, runner) as unknown as IAnnihilator;
  }
}
