/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOtomsEncoder,
  IOtomsEncoderInterface,
} from "../../../../src/otom/interfaces/IOtomsEncoder";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "radius",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "volume",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "mass",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "density",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "electronegativity",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "metallic",
            type: "bool",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "series",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "periodicTableX",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "periodicTableY",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "universeHash",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "depth",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "distance",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "distanceIndex",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "shell",
                type: "uint256",
              },
              {
                internalType: "uint256[]",
                name: "totalInOuter",
                type: "uint256[]",
              },
              {
                internalType: "uint256[]",
                name: "emptyInOuter",
                type: "uint256[]",
              },
              {
                internalType: "uint256[]",
                name: "filledInOuter",
                type: "uint256[]",
              },
              {
                internalType: "uint256[]",
                name: "ancestors",
                type: "uint256[]",
              },
            ],
            internalType: "struct AtomStructure",
            name: "structure",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "protons",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "neutrons",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "nucleons",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "stability",
                type: "uint256",
              },
              {
                internalType: "string",
                name: "decayType",
                type: "string",
              },
            ],
            internalType: "struct Nucleus",
            name: "nucleus",
            type: "tuple",
          },
        ],
        internalType: "struct Atom",
        name: "_newAtom",
        type: "tuple",
      },
    ],
    name: "encodeAtom",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "id",
            type: "string",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "universeHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "activationEnergy",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "radius",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "strength",
                type: "uint256",
              },
              {
                internalType: "string",
                name: "bondType",
                type: "string",
              },
            ],
            internalType: "struct Bond",
            name: "bond",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "radius",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "volume",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "mass",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "density",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "electronegativity",
                type: "uint256",
              },
              {
                internalType: "bool",
                name: "metallic",
                type: "bool",
              },
              {
                internalType: "string",
                name: "name",
                type: "string",
              },
              {
                internalType: "string",
                name: "series",
                type: "string",
              },
              {
                internalType: "uint256",
                name: "periodicTableX",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "periodicTableY",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "universeHash",
                    type: "bytes32",
                  },
                  {
                    internalType: "uint256",
                    name: "depth",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "distance",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "distanceIndex",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "shell",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256[]",
                    name: "totalInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "emptyInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "filledInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "ancestors",
                    type: "uint256[]",
                  },
                ],
                internalType: "struct AtomStructure",
                name: "structure",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "protons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "neutrons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "nucleons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "stability",
                    type: "uint256",
                  },
                  {
                    internalType: "string",
                    name: "decayType",
                    type: "string",
                  },
                ],
                internalType: "struct Nucleus",
                name: "nucleus",
                type: "tuple",
              },
            ],
            internalType: "struct Atom[]",
            name: "givingAtoms",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "radius",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "volume",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "mass",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "density",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "electronegativity",
                type: "uint256",
              },
              {
                internalType: "bool",
                name: "metallic",
                type: "bool",
              },
              {
                internalType: "string",
                name: "name",
                type: "string",
              },
              {
                internalType: "string",
                name: "series",
                type: "string",
              },
              {
                internalType: "uint256",
                name: "periodicTableX",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "periodicTableY",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "universeHash",
                    type: "bytes32",
                  },
                  {
                    internalType: "uint256",
                    name: "depth",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "distance",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "distanceIndex",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "shell",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256[]",
                    name: "totalInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "emptyInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "filledInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "ancestors",
                    type: "uint256[]",
                  },
                ],
                internalType: "struct AtomStructure",
                name: "structure",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "protons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "neutrons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "nucleons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "stability",
                    type: "uint256",
                  },
                  {
                    internalType: "string",
                    name: "decayType",
                    type: "string",
                  },
                ],
                internalType: "struct Nucleus",
                name: "nucleus",
                type: "tuple",
              },
            ],
            internalType: "struct Atom[]",
            name: "receivingAtoms",
            type: "tuple[]",
          },
          {
            internalType: "uint256",
            name: "electricalConductivity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "thermalConductivity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "toughness",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "hardness",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ductility",
            type: "uint256",
          },
        ],
        internalType: "struct Molecule",
        name: "_newMolecule",
        type: "tuple",
      },
    ],
    name: "encodeMolecule",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "protons",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "neutrons",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nucleons",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "stability",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "decayType",
            type: "string",
          },
        ],
        internalType: "struct Nucleus",
        name: "_newNucleus",
        type: "tuple",
      },
    ],
    name: "encodeNucleus",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "universeHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "depth",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "distance",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "distanceIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "shell",
            type: "uint256",
          },
          {
            internalType: "uint256[]",
            name: "totalInOuter",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "emptyInOuter",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "filledInOuter",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "ancestors",
            type: "uint256[]",
          },
        ],
        internalType: "struct AtomStructure",
        name: "_newStructure",
        type: "tuple",
      },
    ],
    name: "encodeStructure",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "energyFactorBps",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
          {
            internalType: "bytes32",
            name: "seedHash",
            type: "bytes32",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
        ],
        internalType: "struct UniverseInformation",
        name: "_universeInformation",
        type: "tuple",
      },
    ],
    name: "encodeUniverseInformation",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_chemist",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_universeHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_nonce",
        type: "uint256",
      },
    ],
    name: "getMiningHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "id",
            type: "string",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "universeHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "activationEnergy",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "radius",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "strength",
                type: "uint256",
              },
              {
                internalType: "string",
                name: "bondType",
                type: "string",
              },
            ],
            internalType: "struct Bond",
            name: "bond",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "radius",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "volume",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "mass",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "density",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "electronegativity",
                type: "uint256",
              },
              {
                internalType: "bool",
                name: "metallic",
                type: "bool",
              },
              {
                internalType: "string",
                name: "name",
                type: "string",
              },
              {
                internalType: "string",
                name: "series",
                type: "string",
              },
              {
                internalType: "uint256",
                name: "periodicTableX",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "periodicTableY",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "universeHash",
                    type: "bytes32",
                  },
                  {
                    internalType: "uint256",
                    name: "depth",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "distance",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "distanceIndex",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "shell",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256[]",
                    name: "totalInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "emptyInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "filledInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "ancestors",
                    type: "uint256[]",
                  },
                ],
                internalType: "struct AtomStructure",
                name: "structure",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "protons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "neutrons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "nucleons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "stability",
                    type: "uint256",
                  },
                  {
                    internalType: "string",
                    name: "decayType",
                    type: "string",
                  },
                ],
                internalType: "struct Nucleus",
                name: "nucleus",
                type: "tuple",
              },
            ],
            internalType: "struct Atom[]",
            name: "givingAtoms",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "radius",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "volume",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "mass",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "density",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "electronegativity",
                type: "uint256",
              },
              {
                internalType: "bool",
                name: "metallic",
                type: "bool",
              },
              {
                internalType: "string",
                name: "name",
                type: "string",
              },
              {
                internalType: "string",
                name: "series",
                type: "string",
              },
              {
                internalType: "uint256",
                name: "periodicTableX",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "periodicTableY",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "universeHash",
                    type: "bytes32",
                  },
                  {
                    internalType: "uint256",
                    name: "depth",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "distance",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "distanceIndex",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "shell",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256[]",
                    name: "totalInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "emptyInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "filledInOuter",
                    type: "uint256[]",
                  },
                  {
                    internalType: "uint256[]",
                    name: "ancestors",
                    type: "uint256[]",
                  },
                ],
                internalType: "struct AtomStructure",
                name: "structure",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "protons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "neutrons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "nucleons",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "stability",
                    type: "uint256",
                  },
                  {
                    internalType: "string",
                    name: "decayType",
                    type: "string",
                  },
                ],
                internalType: "struct Nucleus",
                name: "nucleus",
                type: "tuple",
              },
            ],
            internalType: "struct Atom[]",
            name: "receivingAtoms",
            type: "tuple[]",
          },
          {
            internalType: "uint256",
            name: "electricalConductivity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "thermalConductivity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "toughness",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "hardness",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ductility",
            type: "uint256",
          },
        ],
        internalType: "struct Molecule",
        name: "_newAtom",
        type: "tuple",
      },
      {
        internalType: "bytes32",
        name: "_miningHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "_tokenUri",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "_universeHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "getMiningMessageHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_chemist",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_universeHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_startingNonce",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_count",
        type: "uint256",
      },
    ],
    name: "getMultipleMiningHashes",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "energyFactorBps",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
          {
            internalType: "bytes32",
            name: "seedHash",
            type: "bytes32",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
        ],
        internalType: "struct UniverseInformation",
        name: "_universeInformation",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "getSeedUniverseMessageHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOtomsEncoder__factory {
  static readonly abi = _abi;
  static createInterface(): IOtomsEncoderInterface {
    return new Interface(_abi) as IOtomsEncoderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOtomsEncoder {
    return new Contract(address, _abi, runner) as unknown as IOtomsEncoder;
  }
}
