/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReactor,
  IReactorInterface,
} from "../../../../src/otom/interfaces/IReactor";

const _abi = [
  {
    inputs: [],
    name: "CannotAnalyseYet",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "InsufficientBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientEnergy",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidAtomId",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSignature",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidUniverseHash",
    type: "error",
  },
  {
    inputs: [],
    name: "NoAtoms",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "NotAnAtom",
    type: "error",
  },
  {
    inputs: [],
    name: "NotReactionOutputOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "ReactionLengthLimitExceeded",
    type: "error",
  },
  {
    inputs: [],
    name: "UsedSignature",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "encoder",
        type: "address",
      },
    ],
    name: "NewEncoder",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "energy",
        type: "address",
      },
    ],
    name: "NewEnergy",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "otoms",
        type: "address",
      },
    ],
    name: "NewOtoms",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "newLimit",
        type: "uint256",
      },
    ],
    name: "NewReactionLengthLimit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "signer",
        type: "address",
      },
    ],
    name: "NewSigner",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "moleculeId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "labTechnician",
        type: "address",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "universeHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "reactionOutputId",
            type: "uint256",
          },
          {
            components: [
              {
                components: [
                  {
                    internalType: "string",
                    name: "id",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "name",
                    type: "string",
                  },
                  {
                    internalType: "bytes32",
                    name: "universeHash",
                    type: "bytes32",
                  },
                  {
                    internalType: "uint256",
                    name: "activationEnergy",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "radius",
                    type: "uint256",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "strength",
                        type: "uint256",
                      },
                      {
                        internalType: "string",
                        name: "bondType",
                        type: "string",
                      },
                    ],
                    internalType: "struct Bond",
                    name: "bond",
                    type: "tuple",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "radius",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "volume",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "mass",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "density",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "electronegativity",
                        type: "uint256",
                      },
                      {
                        internalType: "bool",
                        name: "metallic",
                        type: "bool",
                      },
                      {
                        internalType: "string",
                        name: "name",
                        type: "string",
                      },
                      {
                        internalType: "string",
                        name: "series",
                        type: "string",
                      },
                      {
                        internalType: "uint256",
                        name: "periodicTableX",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "periodicTableY",
                        type: "uint256",
                      },
                      {
                        components: [
                          {
                            internalType: "bytes32",
                            name: "universeHash",
                            type: "bytes32",
                          },
                          {
                            internalType: "uint256",
                            name: "depth",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "distance",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "distanceIndex",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "shell",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256[]",
                            name: "totalInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "emptyInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "filledInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "ancestors",
                            type: "uint256[]",
                          },
                        ],
                        internalType: "struct AtomStructure",
                        name: "structure",
                        type: "tuple",
                      },
                      {
                        components: [
                          {
                            internalType: "uint256",
                            name: "protons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "neutrons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "nucleons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "stability",
                            type: "uint256",
                          },
                          {
                            internalType: "string",
                            name: "decayType",
                            type: "string",
                          },
                        ],
                        internalType: "struct Nucleus",
                        name: "nucleus",
                        type: "tuple",
                      },
                    ],
                    internalType: "struct Atom[]",
                    name: "givingAtoms",
                    type: "tuple[]",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "radius",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "volume",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "mass",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "density",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "electronegativity",
                        type: "uint256",
                      },
                      {
                        internalType: "bool",
                        name: "metallic",
                        type: "bool",
                      },
                      {
                        internalType: "string",
                        name: "name",
                        type: "string",
                      },
                      {
                        internalType: "string",
                        name: "series",
                        type: "string",
                      },
                      {
                        internalType: "uint256",
                        name: "periodicTableX",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "periodicTableY",
                        type: "uint256",
                      },
                      {
                        components: [
                          {
                            internalType: "bytes32",
                            name: "universeHash",
                            type: "bytes32",
                          },
                          {
                            internalType: "uint256",
                            name: "depth",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "distance",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "distanceIndex",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "shell",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256[]",
                            name: "totalInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "emptyInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "filledInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "ancestors",
                            type: "uint256[]",
                          },
                        ],
                        internalType: "struct AtomStructure",
                        name: "structure",
                        type: "tuple",
                      },
                      {
                        components: [
                          {
                            internalType: "uint256",
                            name: "protons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "neutrons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "nucleons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "stability",
                            type: "uint256",
                          },
                          {
                            internalType: "string",
                            name: "decayType",
                            type: "string",
                          },
                        ],
                        internalType: "struct Nucleus",
                        name: "nucleus",
                        type: "tuple",
                      },
                    ],
                    internalType: "struct Atom[]",
                    name: "receivingAtoms",
                    type: "tuple[]",
                  },
                  {
                    internalType: "uint256",
                    name: "electricalConductivity",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "thermalConductivity",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "toughness",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "hardness",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "ductility",
                    type: "uint256",
                  },
                ],
                internalType: "struct Molecule",
                name: "molecule",
                type: "tuple",
              },
              {
                internalType: "string",
                name: "tokenUri",
                type: "string",
              },
            ],
            internalType: "struct MoleculeWithUri[]",
            name: "outputMolecules",
            type: "tuple[]",
          },
          {
            internalType: "uint256[]",
            name: "inputAtomIds",
            type: "uint256[]",
          },
          {
            internalType: "uint256",
            name: "remainingEnergy",
            type: "uint256",
          },
          {
            internalType: "string[]",
            name: "reactionTypes",
            type: "string[]",
          },
          {
            internalType: "bool",
            name: "success",
            type: "bool",
          },
        ],
        indexed: false,
        internalType: "struct ReactionResult",
        name: "reactionResult",
        type: "tuple",
      },
    ],
    name: "ReactionAnalysed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "universeHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "resultId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "labTechnician",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "atomIds",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "energyAmount",
        type: "uint256",
      },
    ],
    name: "ReactionInitiated",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "universeHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "reactionOutputId",
            type: "uint256",
          },
          {
            components: [
              {
                components: [
                  {
                    internalType: "string",
                    name: "id",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "name",
                    type: "string",
                  },
                  {
                    internalType: "bytes32",
                    name: "universeHash",
                    type: "bytes32",
                  },
                  {
                    internalType: "uint256",
                    name: "activationEnergy",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "radius",
                    type: "uint256",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "strength",
                        type: "uint256",
                      },
                      {
                        internalType: "string",
                        name: "bondType",
                        type: "string",
                      },
                    ],
                    internalType: "struct Bond",
                    name: "bond",
                    type: "tuple",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "radius",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "volume",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "mass",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "density",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "electronegativity",
                        type: "uint256",
                      },
                      {
                        internalType: "bool",
                        name: "metallic",
                        type: "bool",
                      },
                      {
                        internalType: "string",
                        name: "name",
                        type: "string",
                      },
                      {
                        internalType: "string",
                        name: "series",
                        type: "string",
                      },
                      {
                        internalType: "uint256",
                        name: "periodicTableX",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "periodicTableY",
                        type: "uint256",
                      },
                      {
                        components: [
                          {
                            internalType: "bytes32",
                            name: "universeHash",
                            type: "bytes32",
                          },
                          {
                            internalType: "uint256",
                            name: "depth",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "distance",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "distanceIndex",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "shell",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256[]",
                            name: "totalInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "emptyInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "filledInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "ancestors",
                            type: "uint256[]",
                          },
                        ],
                        internalType: "struct AtomStructure",
                        name: "structure",
                        type: "tuple",
                      },
                      {
                        components: [
                          {
                            internalType: "uint256",
                            name: "protons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "neutrons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "nucleons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "stability",
                            type: "uint256",
                          },
                          {
                            internalType: "string",
                            name: "decayType",
                            type: "string",
                          },
                        ],
                        internalType: "struct Nucleus",
                        name: "nucleus",
                        type: "tuple",
                      },
                    ],
                    internalType: "struct Atom[]",
                    name: "givingAtoms",
                    type: "tuple[]",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "radius",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "volume",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "mass",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "density",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "electronegativity",
                        type: "uint256",
                      },
                      {
                        internalType: "bool",
                        name: "metallic",
                        type: "bool",
                      },
                      {
                        internalType: "string",
                        name: "name",
                        type: "string",
                      },
                      {
                        internalType: "string",
                        name: "series",
                        type: "string",
                      },
                      {
                        internalType: "uint256",
                        name: "periodicTableX",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "periodicTableY",
                        type: "uint256",
                      },
                      {
                        components: [
                          {
                            internalType: "bytes32",
                            name: "universeHash",
                            type: "bytes32",
                          },
                          {
                            internalType: "uint256",
                            name: "depth",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "distance",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "distanceIndex",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "shell",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256[]",
                            name: "totalInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "emptyInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "filledInOuter",
                            type: "uint256[]",
                          },
                          {
                            internalType: "uint256[]",
                            name: "ancestors",
                            type: "uint256[]",
                          },
                        ],
                        internalType: "struct AtomStructure",
                        name: "structure",
                        type: "tuple",
                      },
                      {
                        components: [
                          {
                            internalType: "uint256",
                            name: "protons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "neutrons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "nucleons",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "stability",
                            type: "uint256",
                          },
                          {
                            internalType: "string",
                            name: "decayType",
                            type: "string",
                          },
                        ],
                        internalType: "struct Nucleus",
                        name: "nucleus",
                        type: "tuple",
                      },
                    ],
                    internalType: "struct Atom[]",
                    name: "receivingAtoms",
                    type: "tuple[]",
                  },
                  {
                    internalType: "uint256",
                    name: "electricalConductivity",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "thermalConductivity",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "toughness",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "hardness",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "ductility",
                    type: "uint256",
                  },
                ],
                internalType: "struct Molecule",
                name: "molecule",
                type: "tuple",
              },
              {
                internalType: "string",
                name: "tokenUri",
                type: "string",
              },
            ],
            internalType: "struct MoleculeWithUri[]",
            name: "outputMolecules",
            type: "tuple[]",
          },
          {
            internalType: "uint256[]",
            name: "inputAtomIds",
            type: "uint256[]",
          },
          {
            internalType: "uint256",
            name: "remainingEnergy",
            type: "uint256",
          },
          {
            internalType: "string[]",
            name: "reactionTypes",
            type: "string[]",
          },
          {
            internalType: "bool",
            name: "success",
            type: "bool",
          },
        ],
        internalType: "struct ReactionResult[]",
        name: "reactionResults",
        type: "tuple[]",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "analyseReactions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "atomIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "energyAmount",
        type: "uint256",
      },
    ],
    name: "initiateReaction",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReactor__factory {
  static readonly abi = _abi;
  static createInterface(): IReactorInterface {
    return new Interface(_abi) as IReactorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IReactor {
    return new Contract(address, _abi, runner) as unknown as IReactor;
  }
}
