/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type BondStruct = { strength: BigNumberish; bondType: string };

export type BondStructOutput = [strength: bigint, bondType: string] & {
  strength: bigint;
  bondType: string;
};

export type AtomStructureStruct = {
  universeHash: BytesLike;
  depth: BigNumberish;
  distance: BigNumberish;
  distanceIndex: BigNumberish;
  shell: BigNumberish;
  totalInOuter: BigNumberish[];
  emptyInOuter: BigNumberish[];
  filledInOuter: BigNumberish[];
  ancestors: BigNumberish[];
};

export type AtomStructureStructOutput = [
  universeHash: string,
  depth: bigint,
  distance: bigint,
  distanceIndex: bigint,
  shell: bigint,
  totalInOuter: bigint[],
  emptyInOuter: bigint[],
  filledInOuter: bigint[],
  ancestors: bigint[]
] & {
  universeHash: string;
  depth: bigint;
  distance: bigint;
  distanceIndex: bigint;
  shell: bigint;
  totalInOuter: bigint[];
  emptyInOuter: bigint[];
  filledInOuter: bigint[];
  ancestors: bigint[];
};

export type NucleusStruct = {
  protons: BigNumberish;
  neutrons: BigNumberish;
  nucleons: BigNumberish;
  stability: BigNumberish;
  decayType: string;
};

export type NucleusStructOutput = [
  protons: bigint,
  neutrons: bigint,
  nucleons: bigint,
  stability: bigint,
  decayType: string
] & {
  protons: bigint;
  neutrons: bigint;
  nucleons: bigint;
  stability: bigint;
  decayType: string;
};

export type AtomStruct = {
  radius: BigNumberish;
  volume: BigNumberish;
  mass: BigNumberish;
  density: BigNumberish;
  electronegativity: BigNumberish;
  metallic: boolean;
  name: string;
  series: string;
  periodicTableX: BigNumberish;
  periodicTableY: BigNumberish;
  structure: AtomStructureStruct;
  nucleus: NucleusStruct;
};

export type AtomStructOutput = [
  radius: bigint,
  volume: bigint,
  mass: bigint,
  density: bigint,
  electronegativity: bigint,
  metallic: boolean,
  name: string,
  series: string,
  periodicTableX: bigint,
  periodicTableY: bigint,
  structure: AtomStructureStructOutput,
  nucleus: NucleusStructOutput
] & {
  radius: bigint;
  volume: bigint;
  mass: bigint;
  density: bigint;
  electronegativity: bigint;
  metallic: boolean;
  name: string;
  series: string;
  periodicTableX: bigint;
  periodicTableY: bigint;
  structure: AtomStructureStructOutput;
  nucleus: NucleusStructOutput;
};

export type MoleculeStruct = {
  id: string;
  name: string;
  universeHash: BytesLike;
  activationEnergy: BigNumberish;
  radius: BigNumberish;
  bond: BondStruct;
  givingAtoms: AtomStruct[];
  receivingAtoms: AtomStruct[];
  electricalConductivity: BigNumberish;
  thermalConductivity: BigNumberish;
  toughness: BigNumberish;
  hardness: BigNumberish;
  ductility: BigNumberish;
};

export type MoleculeStructOutput = [
  id: string,
  name: string,
  universeHash: string,
  activationEnergy: bigint,
  radius: bigint,
  bond: BondStructOutput,
  givingAtoms: AtomStructOutput[],
  receivingAtoms: AtomStructOutput[],
  electricalConductivity: bigint,
  thermalConductivity: bigint,
  toughness: bigint,
  hardness: bigint,
  ductility: bigint
] & {
  id: string;
  name: string;
  universeHash: string;
  activationEnergy: bigint;
  radius: bigint;
  bond: BondStructOutput;
  givingAtoms: AtomStructOutput[];
  receivingAtoms: AtomStructOutput[];
  electricalConductivity: bigint;
  thermalConductivity: bigint;
  toughness: bigint;
  hardness: bigint;
  ductility: bigint;
};

export type MoleculeWithUriStruct = {
  molecule: MoleculeStruct;
  tokenUri: string;
};

export type MoleculeWithUriStructOutput = [
  molecule: MoleculeStructOutput,
  tokenUri: string
] & { molecule: MoleculeStructOutput; tokenUri: string };

export type ReactionResultStruct = {
  universeHash: BytesLike;
  reactionOutputId: BigNumberish;
  outputMolecules: MoleculeWithUriStruct[];
  inputAtomIds: BigNumberish[];
  remainingEnergy: BigNumberish;
  reactionTypes: string[];
  success: boolean;
};

export type ReactionResultStructOutput = [
  universeHash: string,
  reactionOutputId: bigint,
  outputMolecules: MoleculeWithUriStructOutput[],
  inputAtomIds: bigint[],
  remainingEnergy: bigint,
  reactionTypes: string[],
  success: boolean
] & {
  universeHash: string;
  reactionOutputId: bigint;
  outputMolecules: MoleculeWithUriStructOutput[];
  inputAtomIds: bigint[];
  remainingEnergy: bigint;
  reactionTypes: string[];
  success: boolean;
};

export interface ReactorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "analyseReactions"
      | "encoder"
      | "energy"
      | "getAnalyseReactionsMessageHash"
      | "initialize"
      | "initiateReaction"
      | "onERC1155BatchReceived"
      | "onERC1155Received"
      | "otoms"
      | "owner"
      | "pendingOwner"
      | "reactionLengthLimit"
      | "reactionOutputs"
      | "renounceOwnership"
      | "setEncoder"
      | "setEnergy"
      | "setOtoms"
      | "setReactionLengthLimit"
      | "setSigner"
      | "supportsInterface"
      | "transferOwnership"
      | "usedSignature"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "NewEncoder"
      | "NewEnergy"
      | "NewOtoms"
      | "NewReactionLengthLimit"
      | "NewSigner"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "ReactionAnalysed"
      | "ReactionInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "analyseReactions",
    values: [ReactionResultStruct[], BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "encoder", values?: undefined): string;
  encodeFunctionData(functionFragment: "energy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAnalyseReactionsMessageHash",
    values: [ReactionResultStruct[], BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateReaction",
    values: [BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "otoms", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reactionLengthLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reactionOutputs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEncoder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEnergy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOtoms",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReactionLengthLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedSignature",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "analyseReactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "encoder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "energy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAnalyseReactionsMessageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateReaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "otoms", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactionLengthLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactionOutputs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEncoder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setEnergy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOtoms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReactionLengthLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedSignature",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewEncoderEvent {
  export type InputTuple = [encoder: AddressLike];
  export type OutputTuple = [encoder: string];
  export interface OutputObject {
    encoder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewEnergyEvent {
  export type InputTuple = [energy: AddressLike];
  export type OutputTuple = [energy: string];
  export interface OutputObject {
    energy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewOtomsEvent {
  export type InputTuple = [otoms: AddressLike];
  export type OutputTuple = [otoms: string];
  export interface OutputObject {
    otoms: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewReactionLengthLimitEvent {
  export type InputTuple = [newLimit: BigNumberish];
  export type OutputTuple = [newLimit: bigint];
  export interface OutputObject {
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewSignerEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReactionAnalysedEvent {
  export type InputTuple = [
    moleculeId: BigNumberish,
    labTechnician: AddressLike,
    reactionResult: ReactionResultStruct
  ];
  export type OutputTuple = [
    moleculeId: bigint,
    labTechnician: string,
    reactionResult: ReactionResultStructOutput
  ];
  export interface OutputObject {
    moleculeId: bigint;
    labTechnician: string;
    reactionResult: ReactionResultStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReactionInitiatedEvent {
  export type InputTuple = [
    universeHash: BytesLike,
    resultId: BigNumberish,
    labTechnician: AddressLike,
    atomIds: BigNumberish[],
    energyAmount: BigNumberish
  ];
  export type OutputTuple = [
    universeHash: string,
    resultId: bigint,
    labTechnician: string,
    atomIds: bigint[],
    energyAmount: bigint
  ];
  export interface OutputObject {
    universeHash: string;
    resultId: bigint;
    labTechnician: string;
    atomIds: bigint[];
    energyAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Reactor extends BaseContract {
  connect(runner?: ContractRunner | null): Reactor;
  waitForDeployment(): Promise<this>;

  interface: ReactorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  analyseReactions: TypedContractMethod<
    [
      reactionResults: ReactionResultStruct[],
      expiry: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  encoder: TypedContractMethod<[], [string], "view">;

  energy: TypedContractMethod<[], [string], "view">;

  getAnalyseReactionsMessageHash: TypedContractMethod<
    [
      reactionResults: ReactionResultStruct[],
      expiry: BigNumberish,
      sender: AddressLike
    ],
    [string],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      signer: AddressLike,
      _encoder: AddressLike,
      _reactionOutputs: AddressLike,
      _reactionLengthLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  initiateReaction: TypedContractMethod<
    [atomIds: BigNumberish[], energyAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  onERC1155BatchReceived: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "view"
  >;

  onERC1155Received: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "view"
  >;

  otoms: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  reactionLengthLimit: TypedContractMethod<[], [bigint], "view">;

  reactionOutputs: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setEncoder: TypedContractMethod<
    [_encoder: AddressLike],
    [void],
    "nonpayable"
  >;

  setEnergy: TypedContractMethod<[_energy: AddressLike], [void], "nonpayable">;

  setOtoms: TypedContractMethod<[_otoms: AddressLike], [void], "nonpayable">;

  setReactionLengthLimit: TypedContractMethod<
    [newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usedSignature: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "analyseReactions"
  ): TypedContractMethod<
    [
      reactionResults: ReactionResultStruct[],
      expiry: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encoder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "energy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAnalyseReactionsMessageHash"
  ): TypedContractMethod<
    [
      reactionResults: ReactionResultStruct[],
      expiry: BigNumberish,
      sender: AddressLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      signer: AddressLike,
      _encoder: AddressLike,
      _reactionOutputs: AddressLike,
      _reactionLengthLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initiateReaction"
  ): TypedContractMethod<
    [atomIds: BigNumberish[], energyAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC1155BatchReceived"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "onERC1155Received"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "otoms"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reactionLengthLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reactionOutputs"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEncoder"
  ): TypedContractMethod<[_encoder: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEnergy"
  ): TypedContractMethod<[_energy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOtoms"
  ): TypedContractMethod<[_otoms: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReactionLengthLimit"
  ): TypedContractMethod<[newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedSignature"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "NewEncoder"
  ): TypedContractEvent<
    NewEncoderEvent.InputTuple,
    NewEncoderEvent.OutputTuple,
    NewEncoderEvent.OutputObject
  >;
  getEvent(
    key: "NewEnergy"
  ): TypedContractEvent<
    NewEnergyEvent.InputTuple,
    NewEnergyEvent.OutputTuple,
    NewEnergyEvent.OutputObject
  >;
  getEvent(
    key: "NewOtoms"
  ): TypedContractEvent<
    NewOtomsEvent.InputTuple,
    NewOtomsEvent.OutputTuple,
    NewOtomsEvent.OutputObject
  >;
  getEvent(
    key: "NewReactionLengthLimit"
  ): TypedContractEvent<
    NewReactionLengthLimitEvent.InputTuple,
    NewReactionLengthLimitEvent.OutputTuple,
    NewReactionLengthLimitEvent.OutputObject
  >;
  getEvent(
    key: "NewSigner"
  ): TypedContractEvent<
    NewSignerEvent.InputTuple,
    NewSignerEvent.OutputTuple,
    NewSignerEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReactionAnalysed"
  ): TypedContractEvent<
    ReactionAnalysedEvent.InputTuple,
    ReactionAnalysedEvent.OutputTuple,
    ReactionAnalysedEvent.OutputObject
  >;
  getEvent(
    key: "ReactionInitiated"
  ): TypedContractEvent<
    ReactionInitiatedEvent.InputTuple,
    ReactionInitiatedEvent.OutputTuple,
    ReactionInitiatedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "NewEncoder(address)": TypedContractEvent<
      NewEncoderEvent.InputTuple,
      NewEncoderEvent.OutputTuple,
      NewEncoderEvent.OutputObject
    >;
    NewEncoder: TypedContractEvent<
      NewEncoderEvent.InputTuple,
      NewEncoderEvent.OutputTuple,
      NewEncoderEvent.OutputObject
    >;

    "NewEnergy(address)": TypedContractEvent<
      NewEnergyEvent.InputTuple,
      NewEnergyEvent.OutputTuple,
      NewEnergyEvent.OutputObject
    >;
    NewEnergy: TypedContractEvent<
      NewEnergyEvent.InputTuple,
      NewEnergyEvent.OutputTuple,
      NewEnergyEvent.OutputObject
    >;

    "NewOtoms(address)": TypedContractEvent<
      NewOtomsEvent.InputTuple,
      NewOtomsEvent.OutputTuple,
      NewOtomsEvent.OutputObject
    >;
    NewOtoms: TypedContractEvent<
      NewOtomsEvent.InputTuple,
      NewOtomsEvent.OutputTuple,
      NewOtomsEvent.OutputObject
    >;

    "NewReactionLengthLimit(uint256)": TypedContractEvent<
      NewReactionLengthLimitEvent.InputTuple,
      NewReactionLengthLimitEvent.OutputTuple,
      NewReactionLengthLimitEvent.OutputObject
    >;
    NewReactionLengthLimit: TypedContractEvent<
      NewReactionLengthLimitEvent.InputTuple,
      NewReactionLengthLimitEvent.OutputTuple,
      NewReactionLengthLimitEvent.OutputObject
    >;

    "NewSigner(address)": TypedContractEvent<
      NewSignerEvent.InputTuple,
      NewSignerEvent.OutputTuple,
      NewSignerEvent.OutputObject
    >;
    NewSigner: TypedContractEvent<
      NewSignerEvent.InputTuple,
      NewSignerEvent.OutputTuple,
      NewSignerEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReactionAnalysed(uint256,address,tuple)": TypedContractEvent<
      ReactionAnalysedEvent.InputTuple,
      ReactionAnalysedEvent.OutputTuple,
      ReactionAnalysedEvent.OutputObject
    >;
    ReactionAnalysed: TypedContractEvent<
      ReactionAnalysedEvent.InputTuple,
      ReactionAnalysedEvent.OutputTuple,
      ReactionAnalysedEvent.OutputObject
    >;

    "ReactionInitiated(bytes32,uint256,address,uint256[],uint256)": TypedContractEvent<
      ReactionInitiatedEvent.InputTuple,
      ReactionInitiatedEvent.OutputTuple,
      ReactionInitiatedEvent.OutputObject
    >;
    ReactionInitiated: TypedContractEvent<
      ReactionInitiatedEvent.InputTuple,
      ReactionInitiatedEvent.OutputTuple,
      ReactionInitiatedEvent.OutputObject
    >;
  };
}
